name: Automatic GitHub Pages generation

on:
  # Trigger on page_build, as well as release, fork, push, watch and issues events
  page_build:
  release:
  fork:
  push:
  watch:
  issues:
    types:
      - opened
      - closed
      - edited
      - deleted
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # The branch where the templates are stored
        # (if not present, uses the 'master' branch)
        # (recomended: use the same branch configured to be used in GH Pages)
        ref: 'gh-pages'
    - uses: itamarc/action-itemplate-ghpages@v1
      with:
        templates_folder: 'templates'
        allow_templates_subfolders: 'false'
        snippets_folder: 'snippets'
        pages_branch: 'gh-pages'
        pages_folder: 'docs'
        # Change to your time zone
        timezone: 'America/Sao_Paulo'
        max_issues: '5'
        max_collaborators: '20'
        publish_readme_md: 'true'
        content_to_copy: ''
        syntax_highlight_enable: 'true'
        syntax_highlight_theme: 'default'
        log_level: 'INFO'
      env:
        # Needed to publish the pages
        GITHUB_TOKEN: ${{ secrets.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 }}
